CREATE OR REPLACE VIEW properties_by_year AS
SELECT
	DATE_PART('YEAR', TO_DATE(ALBUM_RELEASE_DATE, 'DD/MM/YYY')) AS ALBUM_YEAR,
	AVG(DANCEABILITY) AS AVG_DANCEABILITY,
	AVG(ENERGY) AS AVG_ENERGY,
	AVG(KEY) AS AVG_KEY,
	AVG(LOUDNESS) AS AVG_LOUDNESS,
	AVG(SPEECHINESS) AS AVG_SPEECHINESS,
	AVG(ACOUSTICNESS) AS AVG_ACOUSTICNESS,
	AVG(INSTRUMENTALNESS) AS AVG_INSTRUMENTALNESS,
	AVG(LIVENESS) AS AVG_LIVENESS,
	AVG(VALENCE) AS AVG_VALENCE,
	AVG(TEMPO) AS AVG_TEMPO
FROM
	AS_CAPSTONE
GROUP BY
	ALBUM_YEAR
ORDER BY
	ALBUM_YEAR;